version: '3'
services:
  node:
    build: .
    container_name: node
    environment:
      - PORT=3000
    ports:
      - 3000:3000
    networks:
      - my-network

networks:
  my-network:
    driver: bridge