version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=hola
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_DATABASE=test
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    networks:
      - my-network

  node:
    build: .
    environment:
      - PORT=3005
      - MONGODB_URI=mongodb://mongo/test
    ports:
      - 3005:3005
    volumes:
      - .:/app/
      - /app/node_modules/
      - /app/deploy/
    depends_on:
      - mongo
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
 mongodb: