version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: hola
      MONGO_INITDB_DATABASE: test
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    networks:
      - my-network
    restart: always
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: hola
      ME_CONFIG_MONGODB_URL: mongodb://root:hola@mongo:27017/
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - my-network

  node:
    build: .
    environment:
      - PORT=3005
      - MONGODB_URI=mongodb://root:hola@mongo/
    ports:
      - 3005:3005
    volumes:
      - .:/app/
      - /app/node_modules/
      - /app/deploy/
    depends_on:
      - mongo
    networks:
      - my-network
      - external-net

networks:
  my-network:
    driver: bridge
  external-net:
    external: 
      name: ubademy

volumes:
 mongodb: